__title__ = "pptx_tables"
__description__ = "Use pptx-tables to create tables more easily through python-pptx."
__version__ = "0.1.0"
__author__ = "Liam Cryan"
__author_email__ = "data.handyman.01@gmail.com"
__url__ = "http://github.com/liamcryan/pptx-tables"
