__title__ = "Python-pptx-tables"
__description__ = "Use Python-pptx-tables to create tables more easily through Python-pptx."
__version__ = "0.0.0"
__author__ = "Liam Cryan"
__author_email__ = "data.handyman.01@gmail.com"
