__title__ = "pptx-tables"
__description__ = "Use pptx-tables to create tables more easily through python-pptx."
__version__ = "0.0.0"
__author__ = "Liam Cryan"
__author_email__ = "table_data.handyman.01@gmail.com"
